spring:
    datasource:
        username: root
        password: F84f865205!
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/planhub?serverTimezone=UTC&characterEncoding=UTF-8
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        database: mysql
        properties:
            hibernate:
                format_sql: true
    # 콘솔 확인 을 위한 always
    output:
        ansi:
            enabled: always

# 파라미터 확인을 위한 trace
logging:
    level:
        org.hibernate.type: trace