server:
  port: 8081

spring:
  datasource:
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/planhub?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    generate-ddl: false

logging:
  level:
    org.hibernate.type: trace
